<?php

use Drupal\Core\Form\FormStateInterface;

function marucha_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    if ($form_id == 'comment_comment_form') {
        $form['actions']['submit']['#value'] = t('Comment!');
    }
}

/**
 * Implements hook_cron().
 * 
 */
function marucha_cron() {

    $type = \Drupal::service('plugin.manager.tapioca');

    // 利用可能なプラグイン一覧を取得
    $plugin_definitions = $type->getDefinitions();

    // 特定のプラグイン定義を取得
    // $plugin_definition = $type->getDefinition('tapioca_milk_tea');

    $plugin_definition = reset($plugin_definitions);

    \Drupal::messenger()->addStatus('特定のプラグイン定義を取得しました！' . $plugin_definition['id']);

    // プラグインの構成済みインスタンスの作成
    $plugin = $type -> createInstance($plugin_definition['id'], ['of' => 'configuration values']);

    \Drupal::messenger() -> addStatus($plugin->getOrder());

}

?>